set role MUDENGINE_BEING;

create sequence MUDENGINE_BEING.MUD_BEING_SEQ;

CREATE TABLE MUDENGINE_BEING.MUD_ATTRIBUTE (
		ATTR_CODE		varchar(6) not null,
		NAME			varchar(30) not null,
		DESCRIPTION		varchar(100),		
		CONSTRAINT MUD_ATTRIBUTES_PK PRIMARY KEY (ATTR_CODE)
);

CREATE TABLE MUDENGINE_BEING.MUD_SLOT (
		SLOT_CODE		varchar(5) not null,
		NAME			varchar(30) not null,
		DESCRIPTION		varchar(100),		
		CONSTRAINT MUD_SLOT_PK PRIMARY KEY (SLOT_CODE)
);


CREATE TABLE MUDENGINE_BEING.MUD_SKILL_CATEGORY (
		CATEGORY_CODE	varchar(5) not null,
		NAME			varchar(30) not null,
		ATTR_CODE_BASED	varchar(5),
		DESCRIPTION		varchar(100),		
		CONSTRAINT MUD_SKILL_CATG_PK PRIMARY KEY (CATEGORY_CODE),
		FOREIGN KEY (ATTR_CODE_BASED) REFERENCES MUDENGINE_BEING.MUD_ATTRIBUTE(ATTR_CODE)
);
		
CREATE TABLE MUDENGINE_BEING.MUD_SKILL (
		SKILL_CODE		varchar(20) not null,
		CATEGORY_CODE	varchar(5) not null,
		NAME			varchar(30) not null,
		DESCRIPTION		varchar(100),		
		CONSTRAINT MUD_SKILL_PK PRIMARY KEY (SKILL_CODE),
		FOREIGN KEY (CATEGORY_CODE) REFERENCES MUDENGINE_BEING.MUD_SKILL_CATEGORY(CATEGORY_CODE)
);

CREATE TABLE MUDENGINE_BEING.MUD_BEING_CLASS (
		BEING_CLASS_CODE	varchar(20) not null,
		NAME				varchar(30) not null,
		DESCRIPTION     	varchar(200),
		SIZE				integer,
		WEIGHT_CAPACITY 	integer,
		CONSTRAINT MUD_BEING_CLASS_PK PRIMARY KEY (BEING_CLASS_CODE)
);
		
CREATE TABLE MUDENGINE_BEING.MUD_BEING_CLASS_ATTR (
		BEING_CLASS_CODE	varchar(20) not null,
		ATTR_CODE			varchar(5) not null,
		ATTR_VALUE			integer not null default 0,
		CONSTRAINT MUD_BEING_CLASS_ATTR_PK PRIMARY KEY (BEING_CLASS_CODE, ATTR_CODE),
		FOREIGN KEY (BEING_CLASS_CODE) REFERENCES MUDENGINE_BEING.MUD_BEING_CLASS(BEING_CLASS_CODE) on delete cascade
);

CREATE TABLE MUDENGINE_BEING.MUD_BEING_CLASS_SKILL (
		BEING_CLASS_CODE	varchar(20) not null,
		SKILL_CODE			varchar(20) not null,
		SKILL_VALUE			integer not null default 0,
		CONSTRAINT MUD_BEING_CLASS_SKILLS_PK PRIMARY KEY (BEING_CLASS_CODE, SKILL_CODE),
		FOREIGN KEY (BEING_CLASS_CODE) REFERENCES MUDENGINE_BEING.MUD_BEING_CLASS(BEING_CLASS_CODE) on delete cascade
);

CREATE TABLE MUDENGINE_BEING.MUD_BEING_CLASS_SLOT (
		BEING_CLASS_CODE	varchar(20) not null,
		SLOT_CODE			varchar(20) not null,
		CONSTRAINT MUD_BEING_CLASS_SLOT_PK PRIMARY KEY (BEING_CLASS_CODE, SLOT_CODE),
		FOREIGN KEY (BEING_CLASS_CODE) REFERENCES MUDENGINE_BEING.MUD_BEING_CLASS(BEING_CLASS_CODE) on delete cascade
);



CREATE TABLE MUDENGINE_BEING.MUD_BEING (
		BEING_CODE			bigint not null,
		being_class_being_class_code	varchar(20) not null,
		BEING_TYPE			integer not null,
		NAME				varchar(50),
		PLAYER_ID			bigint,		
		CURRENT_WORLD		varchar(30) not null,
		CURRENT_PLACE		integer not null,
		QUANTITY			integer not null default 1,
		FOREIGN KEY (being_class_being_class_code) REFERENCES MUDENGINE_BEING.MUD_BEING_CLASS(BEING_CLASS_CODE),
		CONSTRAINT MUD_BEING_PK PRIMARY KEY (BEING_CODE)
);

CREATE TABLE MUDENGINE_BEING.MUD_BEING_ATTR (
		BEING_CODE		bigint not null,
		ATTR_CODE		varchar(5) not null,
		ATTR_VALUE		integer not null,
		CONSTRAINT MUD_BEING_ATTR_PK PRIMARY KEY (BEING_CODE, ATTR_CODE),
		FOREIGN KEY (BEING_CODE) REFERENCES MUDENGINE_BEING.MUD_BEING(BEING_CODE) on delete cascade,
		FOREIGN KEY (ATTR_CODE) REFERENCES MUDENGINE_BEING.MUD_ATTRIBUTE(ATTR_CODE)
);

CREATE TABLE MUDENGINE_BEING.MUD_BEING_SKILL (
		BEING_CODE		bigint not null,
		SKILL_CODE		varchar(20) not null,
		SKILL_VALUE 	integer not null,
		CONSTRAINT MUD_BEING_SKILLS_PK PRIMARY KEY (BEING_CODE, SKILL_CODE),
		FOREIGN KEY (BEING_CODE) REFERENCES MUDENGINE_BEING.MUD_BEING(BEING_CODE) on delete cascade,
		FOREIGN KEY (SKILL_CODE) REFERENCES MUDENGINE_BEING.MUD_SKILL(SKILL_CODE)
);

CREATE TABLE MUDENGINE_BEING.MUD_BEING_SLOT (
		BEING_CODE		bigint not null,
		SLOT_CODE		varchar(20) not null,
		ITEM_CODE		bigint,
		CONSTRAINT MUD_BEING_SLOT_PK PRIMARY KEY (BEING_CODE, SLOT_CODE),
		FOREIGN KEY (BEING_CODE) REFERENCES MUDENGINE_BEING.MUD_BEING(BEING_CODE) on delete cascade,
		FOREIGN KEY (SLOT_CODE) REFERENCES MUDENGINE_BEING.MUD_SLOT(SLOT_CODE)
);


CREATE TABLE MUDENGINE_BEING.MUD_BEING_ATTR_MODIFIER (
		BEING_CODE		bigint not null,
		ATTR_CODE		varchar(5) not null,
		ORIGIN_CODE		varchar(20) not null,
		ORIGIN_TYPE		varchar(30) not null,
		
		ATTR_OFFSET		real not null,
		END_TURN		integer,
		CONSTRAINT MUD_BEING_ATTR_MOD_PK PRIMARY KEY (BEING_CODE, ATTR_CODE, ORIGIN_CODE, ORIGIN_TYPE),
		FOREIGN KEY (BEING_CODE) REFERENCES MUDENGINE_BEING.MUD_BEING(BEING_CODE)  on delete cascade,
		FOREIGN KEY (ATTR_CODE) REFERENCES MUDENGINE_BEING.MUD_ATTRIBUTE(ATTR_CODE)
);

CREATE TABLE MUDENGINE_BEING.MUD_BEING_SKILL_MODIFIER (
		BEING_CODE		bigint not null,
		SKILL_CODE		varchar(20) not null,
		ORIGIN_CODE		varchar(20) not null,
		ORIGIN_TYPE		varchar(30) not null,
		SKILL_OFFSET 	real not null,
		END_TURN		integer,
		CONSTRAINT MUD_BEING_SKILL_MOD_PK PRIMARY KEY (BEING_CODE, SKILL_CODE, ORIGIN_CODE, ORIGIN_TYPE),
		FOREIGN KEY (BEING_CODE) REFERENCES MUDENGINE_BEING.MUD_BEING(BEING_CODE)  on delete cascade,
		FOREIGN KEY (SKILL_CODE) REFERENCES MUDENGINE_BEING.MUD_SKILL(SKILL_CODE)
);

CREATE TABLE MUDENGINE_BEING.MUD_BEING_MESSAGE (
	BEING_CODE		bigint not null,
	CREATE_DATE		timestamp not null default current_timestamp,
	MESSAGE			varchar(1024) not null,
	READ_FLAG		boolean,
	SENDER_CODE		bigint,

	CONSTRAINT MUD_BEING_MESSAGE_PK PRIMARY KEY (BEING_CODE, CREATE_DATE),
	FOREIGN KEY (BEING_CODE) REFERENCES MUDENGINE_BEING.MUD_BEING(BEING_CODE) on delete cascade,
	FOREIGN KEY (SENDER_CODE) REFERENCES MUDENGINE_BEING.MUD_BEING(BEING_CODE) on delete cascade
);
