set role MUDENGINE_ACTION;

DROP TABLE MUDENGINE_ACTION.MUD_ACTION;
DROP SEQUENCE MUDENGINE_ACTION.MUD_ACTION_SEQ;

DROP TABLE MUDENGINE_ACTION.MUD_ACTION_CLASS_CMD_PARAMETER;
DROP TABLE MUDENGINE_ACTION.MUD_ACTION_CLASS_CMD;
DROP TABLE MUDENGINE_ACTION.MUD_ACTION_CLASS_EFFECT;
DROP TABLE MUDENGINE_ACTION.MUD_ACTION_CLASS_PREREQ;
DROP TABLE MUDENGINE_ACTION.MUD_ACTION_CLASS;

