set role mudengine_item;

DROP TABLE MUDENGINE_ITEM.MUD_ITEM_ATTR;
DROP TABLE MUDENGINE_ITEM.MUD_ITEM;

DROP TABLE MUDENGINE_ITEM.MUD_ITEM_CLASS_ATTR;
DROP TABLE MUDENGINE_ITEM.MUD_ITEM_CLASS;

DROP SEQUENCE mudengine_item.MUD_ITEM_SEQ;

reset role;