set role MUDENGINE_ACTION;

DROP TABLE MUDENGINE_ACTION.MUD_ACTION_CLASS_EFFECT;
DROP TABLE MUDENGINE_ACTION.MUD_ACTION_CLASS_COST;
DROP TABLE MUDENGINE_ACTION.MUD_ACTION_CLASS_PREREQ;
DROP TABLE MUDENGINE_ACTION.MUD_ACTION_CLASS;

DROP TABLE MUDENGINE_ACTION.MUD_ACTION;
DROP SEQUENCE MUDENGINE_ACTION.MUD_ACTION_SEQ;