set role MUDENGINE_BEING;

DROP TABLE MUDENGINE_BEING.MUD_BEING_ATTR;
DROP TABLE MUDENGINE_BEING.MUD_BEING_SKILL;
DROP TABLE MUDENGINE_BEING.MUD_BEING_ATTR_MODIFIER;
DROP TABLE MUDENGINE_BEING.MUD_BEING_SKILL_MODIFIER;

DROP TABLE MUDENGINE_BEING.MUD_BEING_ITEM;
DROP TABLE MUDENGINE_BEING.MUD_BEING;

DROP TABLE MUDENGINE_BEING.MUD_PLAYER;

DROP TABLE MUDENGINE_BEING.MUD_SKILL;
DROP TABLE MUDENGINE_BEING.MUD_SKILL_CATEGORY;
DROP TABLE MUDENGINE_BEING.MUD_ATTRIBUTE;

DROP SEQUENCE MUDENGINE_BEING.MUD_BEING_SEQ;