set role mudengine_item;

CREATE TABLE MUDENGINE_ITEM.MUD_ITEM_CLASS (
		ITEM_CLASS     varchar(30) not null,
		SIZE			real not null,
		WEIGHT			real not null,
		DURABILITY		integer,
		CONSTRAINT MUD_ITEM_CLASS_PK PRIMARY KEY (ITEM_CLASS)
);

CREATE TABLE MUDENGINE_ITEM.MUD_ITEM_CLASS_SKILL (
		ITEM_CLASS		varchar(30) not null,
		SKILL_CODE		varchar(20) not null,
		SKILL_OFFSET	real not null,
		CONSTRAINT MUD_ITEM_CLASS_SKILL_PK PRIMARY KEY (ITEM_CLASS, SKILL_CODE),
		FOREIGN KEY (ITEM_CLASS) REFERENCES MUDENGINE_ITEM.MUD_ITEM_CLASS(ITEM_CLASS)
);

CREATE TABLE MUDENGINE_ITEM.MUD_ITEM_CLASS_ATTR (
		ITEM_CLASS     varchar(30) not null,
		ATTR_CODE		varchar(5) not null,
		ATTR_OFFSET		real not null,
		CONSTRAINT MUD_ITEM_CLASS_ATTR_PK PRIMARY KEY (ITEM_CLASS, ATTR_CODE),
		FOREIGN KEY (ITEM_CLASS) REFERENCES MUDENGINE_ITEM.MUD_ITEM_CLASS(ITEM_CLASS)
);




CREATE TABLE MUDENGINE_ITEM.MUD_ITEM (
		ITEM_CODE		integer not null,
		ITEM_CLASS     	varchar(30) not null,
		USAGE_COUNT		integer,
		NAME			varchar(30) not null,
		DESCRIPTION		varchar(100),
		CONSTRAINT MUD_ITEM_PK PRIMARY KEY (ITEM_CODE),
		FOREIGN KEY (ITEM_CLASS) REFERENCES MUDENGINE_ITEM.MUD_ITEM_CLASS(ITEM_CLASS)
);

CREATE TABLE MUDENGINE_ITEM.MUD_ITEM_SKILL (
		ITEM_CODE		integer not null,
		SKILL_CODE		varchar(20) not null,
		SKILL_OFFSET	real not null,
		CONSTRAINT MUD_ITEM_SKILL_PK PRIMARY KEY (ITEM_CODE, SKILL_CODE),
		FOREIGN KEY (ITEM_CODE) REFERENCES MUDENGINE_ITEM.MUD_ITEM(ITEM_CODE)
);

CREATE TABLE MUDENGINE_ITEM.MUD_ITEM_ATTR (
		ITEM_CODE		integer not null,
		ATTR_CODE		varchar(5) not null,
		ATTR_OFFSET		real not null,
		CONSTRAINT MUD_ITEM_ATTR_PK PRIMARY KEY (ITEM_CODE, ATTR_CODE),
		FOREIGN KEY (ITEM_CODE) REFERENCES MUDENGINE_ITEM.MUD_ITEM(ITEM_CODE)
);

reset role;
