DROP TABLE MUDENGINE_ITEM.MUD_ITEM_ATTR;
DROP TABLE MUDENGINE_ITEM.MUD_ITEM_SKILL;
DROP TABLE MUDENGINE_ITEM.MUD_ITEM;

DROP TABLE MUDENGINE_ITEM.MUD_ITEM_CLASS_ATTR;
DROP TABLE MUDENGINE_ITEM.MUD_ITEM_CLASS_SKILL;
DROP TABLE MUDENGINE_ITEM.MUD_ITEM_CLASS;