set role mudengine_world;

CREATE TABLE mudengine_world.MUD_PLACE_CLASS (
	PLACE_CLASS_CODE	varchar(20) NOT NULL,
	NAME				varchar(30) NOT NULL,
	MOVEMENT_COST		integer not null,
	DESCRIPTION			varchar(500),
	SIZE_CAPACITY		integer,
	WEIGHT_CAPACITY		integer,
	PARENT_CLASS_CODE   varchar(20),
	BUILD_COST			integer,
	BUILD_EFFORT		integer,
	MATERIAL_CODE		varchar(30),
	CONSTRAINT MUD_PLACE_CLASS_PK PRIMARY KEY (PLACE_CLASS_CODE)
);

CREATE TABLE mudengine_world.MUD_PLACE_CLASS_SKILL (
	PLACE_CLASS_CODE	varchar(20) NOT NULL,
	SKILL_CODE		varchar(20) not null,
	SKILL_OFFSET	real NOT NULL,
	CONSTRAINT MUD_PLACE_CLASS_SKILL_PK PRIMARY KEY (PLACE_CLASS_CODE, SKILL_CODE),
	FOREIGN KEY (PLACE_CLASS_CODE) REFERENCES mudengine_world.MUD_PLACE_CLASS(PLACE_CLASS_CODE)
);

CREATE TABLE mudengine_world.MUD_PLACE_CLASS_ATTR (
	PLACE_CLASS_CODE	varchar(20) NOT NULL,
	ATTR_CODE		varchar(5) not null,
	ATTR_OFFSET		real NOT NULL,
	CONSTRAINT MUD_PLACE_CLASS_ATTR_PK PRIMARY KEY (PLACE_CLASS_CODE, ATTR_CODE),
	FOREIGN KEY (PLACE_CLASS_CODE) REFERENCES mudengine_world.MUD_PLACE_CLASS(PLACE_CLASS_CODE)
);

CREATE TABLE mudengine_world.MUD_PLACE  (
	PLACE_CODE			integer NOT NULL,
	PLACE_CLASS_CODE	varchar(20) NOT NULL,
	CONSTRAINT MUD_PLACE_PK PRIMARY KEY (PLACE_CODE),
	FOREIGN KEY (PLACE_CLASS_CODE) REFERENCES mudengine_world.MUD_PLACE_CLASS(PLACE_CLASS_CODE)
);
	
	
CREATE TABLE mudengine_world.MUD_PLACE_EXITS (
	PLACE_CODE			integer NOT NULL,
	DIRECTION			varchar(10) NOT NULL,
	NAME				varchar(50) NOT NULL,
	OPENED				boolean NOT NULL DEFAULT 'true',
	LOCKED				boolean NOT NULL DEFAULT 'false',
	LOCKABLE			boolean NOT NULL DEFAULT 'false',
	VISIBLE				boolean NOT NULL DEFAULT 'true',
	TARGET_PLACE_CODE	integer NOT NULL,
	CONSTRAINT MUD_PLACE_EXITS_PK PRIMARY KEY (PLACE_CODE, DIRECTION),
	FOREIGN KEY (PLACE_CODE) REFERENCES mudengine_world.MUD_PLACE(PLACE_CODE)
);

CREATE TABLE mudengine_world.MUD_PLACE_ITEMS (
	PLACE_CODE		integer NOT NULL,
	ITEM_CODE		integer NOT NULL,
	QTTY			integer NOT NULL DEFAULT 1,
	CONSTRAINT MUD_PLACE_ITEMS_PK PRIMARY KEY (PLACE_CODE, ITEM_CODE),
	FOREIGN KEY (PLACE_CODE) REFERENCES mudengine_world.MUD_PLACE(PLACE_CODE)
);

CREATE TABLE mudengine_world.MUD_PLACE_BEINGS (
	PLACE_CODE		integer NOT NULL,
	BEING_CODE		integer NOT NULL,
	QTTY			integer NOT NULL DEFAULT 1,
	CONSTRAINT MUD_PLACE_BEINGS_PK PRIMARY KEY (PLACE_CODE, BEING_CODE),
	FOREIGN KEY (PLACE_CODE) REFERENCES mudengine_world.MUD_PLACE(PLACE_CODE)
);


CREATE TABLE mudengine_world.MUD_BEING_CLASS (
		BEING_CLASS		varchar(20) not null,
		NAME			varchar(30) not null,
		DESCRIPTION     varchar(200),
		SIZE			integer,
		WEIGHT_CAPACITY integer,
		CONSTRAINT MUD_BEING_CLASS_PK PRIMARY KEY (BEING_CLASS)
);
		
CREATE TABLE mudengine_world.MUD_BEING_CLASS_ATTR (
		BEING_CLASS		varchar(20) not null,
		ATTR_CODE		varchar(5) not null,
		ATTR_VALUE		integer not null default 0,
		CONSTRAINT MUD_BEING_CLASS_ATTR_PK PRIMARY KEY (BEING_CLASS, ATTR_CODE),
		FOREIGN KEY (BEING_CLASS) REFERENCES mudengine_world.MUD_BEING_CLASS(BEING_CLASS)
);

CREATE TABLE mudengine_world.MUD_BEING_CLASS_SKILL (
		BEING_CLASS		varchar(20) not null,
		SKILL_CODE		varchar(20) not null,
		SKILL_VALUE		integer not null default 0,
		CONSTRAINT MUD_BEING_CLASS_SKILLS_PK PRIMARY KEY (BEING_CLASS, SKILL_CODE),
		FOREIGN KEY (BEING_CLASS) REFERENCES mudengine_world.MUD_BEING_CLASS(BEING_CLASS)
);
