set role mudengine_world;

CREATE TABLE mudengine_world.MUD_TERRAIN_CATEGORY (
	CATEGORY_CODE	integer NOT NULL,
	NAME			varchar(30) NOT NULL,
	DESCRIPTION		varchar(50),
	CONSTRAINT MUD_TERRAIN_CATG_PK PRIMARY KEY (CATEGORY_CODE)
);

CREATE TABLE mudengine_world.MUD_TERRAIN_CATG_SKILL (
	CATEGORY_CODE	integer NOT NULL,
	SKILL_CODE		integer NOT NULL,
	SKILL_OFFSET	real NOT NULL,
	CONSTRAINT MUD_TERRAIN_CATG_SKILL_PK PRIMARY KEY (CATEGORY_CODE, SKILL_CODE),
	FOREIGN KEY (CATEGORY_CODE) REFERENCES mudengine_world.MUD_TERRAIN_CATEGORY(CATEGORY_CODE)
);

CREATE TABLE mudengine_world.MUD_TERRAIN_CATG_ATTR (
	CATEGORY_CODE	integer NOT NULL,
	ATTR_CODE		integer NOT NULL,
	ATTR_OFFSET		real NOT NULL,
	CONSTRAINT MUD_TERRAIN_CATG_ATTR_PK PRIMARY KEY (CATEGORY_CODE, ATTR_CODE),
	FOREIGN KEY (CATEGORY_CODE) REFERENCES mudengine_world.MUD_TERRAIN_CATEGORY(CATEGORY_CODE)
);

CREATE TABLE mudengine_world.MUD_TERRAIN (
	TERRAIN_CODE	integer NOT NULL,
	NAME			varchar(30) NOT NULL,
	DESCRIPTION		varchar(500),
	CATEGORY_CODE	integer NOT NULL,
	SIZE_CAPACITY	integer,
	WEIGHT_CAPACITY	integer,	
	CONSTRAINT MUD_TERRAIN_PK PRIMARY KEY (TERRAIN_CODE)
);


CREATE TABLE mudengine_world.MUD_PLACE  (
	PLACE_CODE		integer NOT NULL,
	NAME			varchar(50),
	DESCRIPTION		varchar(500),
	TERRAIN_CODE	integer NOT NULL,
	CONSTRAINT MUD_PLACE_PK PRIMARY KEY (PLACE_CODE),
	FOREIGN KEY (TERRAIN_CODE) REFERENCES mudengine_world.MUD_TERRAIN(TERRAIN_CODE)
);
	
	
CREATE TABLE mudengine_world.MUD_PLACE_EXITS (
	PLACE_CODE			integer NOT NULL,
	DIRECTION			varchar(10) NOT NULL,
	NAME				varchar(50) NOT NULL,
	OPENED				boolean NOT NULL DEFAULT 'true',
	VISIBLE				boolean NOT NULL DEFAULT 'true',
	TARGET_PLACE_CODE	integer NOT NULL,
	CONSTRAINT MUD_PLACE_EXITS_PK PRIMARY KEY (PLACE_CODE, DIRECTION),
	FOREIGN KEY (PLACE_CODE) REFERENCES mudengine_world.MUD_PLACE(PLACE_CODE)
);

CREATE TABLE mudengine_world.MUD_PLACE_ITEMS (
	PLACE_CODE		integer NOT NULL,
	ITEM_CODE		integer NOT NULL,
	QTTY			integer NOT NULL DEFAULT 1,
	CONSTRAINT MUD_PLACE_ITEMS_PK PRIMARY KEY (PLACE_CODE, ITEM_CODE),
	FOREIGN KEY (PLACE_CODE) REFERENCES mudengine_world.MUD_PLACE(PLACE_CODE)
);

CREATE TABLE mudengine_world.MUD_PLACE_BEINGS (
	PLACE_CODE		integer NOT NULL,
	BEING_CODE		integer NOT NULL,
	QTTY			integer NOT NULL DEFAULT 1,
	CONSTRAINT MUD_PLACE_BEINGS_PK PRIMARY KEY (PLACE_CODE, BEING_CODE),
	FOREIGN KEY (PLACE_CODE) REFERENCES mudengine_world.MUD_PLACE(PLACE_CODE)
);


CREATE TABLE mudengine_world.MUD_BEING_CLASS (
		BEING_CLASS		varchar(20) not null,
		NAME			varchar(30) not null,
		DESCRIPTION     varchar(200),
		SIZE			integer,
		WEIGHT_CAPACITY integer,
		CONSTRAINT MUD_BEING_CLASS_PK PRIMARY KEY (BEING_CLASS)
);
		
CREATE TABLE mudengine_world.MUD_BEING_CLASS_ATTR (
		BEING_CLASS		varchar(20) not null,
		ATTR_CODE		varchar(5) not null,
		ATTR_VALUE		integer not null default 0,
		CONSTRAINT MUD_BEING_CLASS_ATTR_PK PRIMARY KEY (BEING_CLASS, ATTR_CODE),
		FOREIGN KEY (BEING_CLASS) REFERENCES mudengine_world.MUD_BEING_CLASS(BEING_CLASS)
);

CREATE TABLE mudengine_world.MUD_BEING_CLASS_SKILLS (
		BEING_CLASS		varchar(20) not null,
		SKILL_CODE		varchar(20) not null,
		SKILL_VALUE		integer not null default 0,
		CONSTRAINT MUD_BEING_CLASS_SKILLS_PK PRIMARY KEY (BEING_CLASS, SKILL_CODE),
		FOREIGN KEY (BEING_CLASS) REFERENCES mudengine_world.MUD_BEING_CLASS(BEING_CLASS)
);
