set role mudengine_data;

DROP TABLE MUDENGINE_DATA.MUD_PLACE_BEINGS;
DROP TABLE MUDENGINE_DATA.MUD_PLACE_ITEMS;
DROP TABLE MUDENGINE_DATA.MUD_PLACE_EXITS;
DROP TABLE MUDENGINE_DATA.MUD_PLACE;

DROP TABLE MUDENGINE_DATA.MUD_TERRAIN_CATG_ATTR;
DROP TABLE MUDENGINE_DATA.MUD_TERRAIN_CATG_SKILL;
DROP TABLE MUDENGINE_DATA.MUD_TERRAIN_CATEGORY;
DROP TABLE MUDENGINE_DATA.MUD_TERRAIN;

DROP TABLE MUDENGINE_DATA.MUD_BEING_CLASS_SKILLS;
DROP TABLE MUDENGINE_DATA.MUD_BEING_CLASS_ATTR;
DROP TABLE MUDENGINE_DATA.MUD_BEING_CLASS;
