DROP TABLE MUDENGINE_PLAYER.MUD_PLAYER_SESSION;
DROP TABLE MUDENGINE_PLAYER.MUD_PLAYER_BEING
DROP TABLE MUDENGINE_PLAYER.MUD_PLAYER;

DROP sequence MUDENGINE_PLAYER.MUD_SESSION_SEQ;
DROP sequence MUDENGINE_PLAYER.MUD_PLAYER_SEQ;

